/** Hebrew first — the product is aimed at Israeli agents. */
export const LANGS = {
  he: {
    dir: 'rtl',
    tour: 'סיור בנכס',
    rooms: 'חדרים',
    size: 'שטח',
    floor: 'קומה',
    sqm: 'מ״ר',
    price: 'מחיר',
    details: 'פרטי הנכס',
    contact: 'דברו איתי',
    call: 'חיוג',
    photos: 'תמונות מהנכס',
    walkHint: 'גרור כדי להסתכל · ג׳ויסטיק כדי ללכת',
    entrance: 'כניסה',
    living: 'סלון ומטבח',
    livingClosed: 'סלון',
    master: 'חדר שינה',
    bedroom2: 'חדר 2',
    bedroom3: 'חדר 3',
    bedroom4: 'חדר 4',
    bath: 'אמבטיה',
    bath2: 'שירותים',
    kitchen: 'מטבח',
    balcony: 'מרפסת',
    openKitchen: 'מטבח פתוח',
    elevator: 'מעלית',
    note: 'הדמיה של תכנית הנכס. התמונות האמיתיות מוצגות בתוך הסיור ובגלריה.',
    studioTitle: 'בונה הסיורים',
    studioSub: 'מלאו את פרטי הנכס, קבלו קישור, שלחו ללקוח',
    property: 'הנכס',
    agentSection: 'פרטי המתווך',
    title: 'כותרת',
    address: 'כתובת',
    bedroomsLabel: 'חדרי שינה',
    bathroomsLabel: 'חדרי רחצה',
    sizeLabel: 'שטח במ״ר',
    floorLabel: 'קומה',
    agentName: 'שם',
    agency: 'משרד',
    phone: 'טלפון',
    preview: 'תצוגה מקדימה',
    createLink: 'צור קישור לשליחה',
    copied: 'הקישור הועתק',
    sendWhatsapp: 'שליחה בוואטסאפ',
    openTour: 'פתח את הסיור',
    linkReady: 'הקישור מוכן',

    /* landing page */
    landTitle: 'הנכס שלכם. סיור תלת־ממדי. קישור אחד.',
    landSub:
      'העלו את התמונות מהנכס, מלאו כמה פרטים, וקבלו קישור שהלקוח פותח בטלפון ומטייל בדירה — בלי אפליקציה, בלי הרשמה, בלי ציוד צילום.',
    landCta: 'התחילו עם התמונות',
    landSecondary: 'לראות סיור לדוגמה',
    landPhotosTitle: 'התמונות מהנכס',
    landPhotosSub: 'הן ייתלו על הקירות בתוך הסיור ויופיעו בגלריה. אפשר גם בלעדיהן.',
    landContinue: 'המשיכו לבניית הסיור',
    landSkip: 'דלגו — אבנה בלי תמונות',
    landStepsTitle: 'איך זה עובד',
    landStep1: 'מעלים תמונות',
    landStep1Body: 'ישר מהטלפון, מהמצלמה או מהמחשב. אנחנו מקטינים אותן כדי שהסיור ייפתח מהר.',
    landStep2: 'ממלאים פרטים',
    landStep2Body: 'חדרים, שטח, קומה, מרפסת. מתוך זה נבנית תכנית דירה שאפשר להסתובב בה.',
    landStep3: 'שולחים קישור',
    landStep3Body: 'קישור אחד בוואטסאפ. הלקוח פותח, מטייל, ומתקשר אליכם מתוך הסיור.',
    landWhyTitle: 'למה זה עובד',
    landWhy1: 'פחות ביקורים מיותרים',
    landWhy1Body: 'מי שמגיע לדירה כבר ראה אותה. נשארים רק הרציניים.',
    landWhy2: 'מוכן בדקה',
    landWhy2Body: 'לא צריך סורק, לא צלם ולא לתאם כניסה לנכס.',
    landWhy3: 'עובד בכל טלפון',
    landWhy3Body: 'דפדפן רגיל. אין מה להוריד ואין במה להירשם.',
    landHonest: 'שקיפות: הסיור הוא הדמיה של תכנית הנכס לפי הפרטים שמילאתם — לא סריקה של הדירה עצמה. התמונות האמיתיות מוצגות בתוכו ובגלריה.',
    landFooter: 'סיורי נכסים תלת־ממדיים למתווכים',

    /* tagging each photo, so the browser can build without a model */
    tagTitle: 'מה רואים בכל תמונה?',
    tagSub: 'הקישו על סוג החדר מתחת לכל תמונה. שתי תמונות של אותו חדר — סמנו את שתיהן.',
    areaLabel: 'שטח הדירה במ״ר',
    areaHint: 'המספר שמופיע במודעה. לפיו מחולקים גדלי החדרים.',
    buildFree: 'בנו את הבית',
    needTags: 'סמנו לפחות תמונה אחת כדי להתחיל.',
    reading2: 'קורא את התמונות…',
    readNote: 'הצבעים, הרצפות והחלונות נקראים מהתמונות שלכם. הרהיטים הם סטנדרטיים — בצבעים שנקראו מהחדר.',
    whatWasRead: 'מה נקרא מהתמונות',
    floorKinds: {
      wood: 'פרקט',
      tile: 'קרמיקה',
      stone: 'אבן',
      carpet: 'שטיח',
      vinyl: 'ויניל',
      concrete: 'בטון',
    },
    hasWindow: 'חלון',
    unknownPhoto: 'לא סומן',
    taggedCount: 'סומנו {n} מתוך {total} תמונות',

    /* reading the photos into a home */
    buildHouse: 'בנו את הבית מהתמונות',
    reading: 'קורא את התמונות…',
    readingStep1: 'מזהה חדרים',
    readingStep2: 'מודד ממדים',
    readingStep3: 'קורא צבעים וחומרים',
    readingStep4: 'בונה את הדירה',
    readingWait: 'זה לוקח חצי דקה עד דקה. אל תסגרו את הדף.',
    surveyDone: 'הבית מוכן',
    surveyRooms: 'זוהו {n} חדרים',
    tryAgain: 'נסו שוב',
    surveyErrors: {
      unreadable: 'לא הצלחתי לזהות בתמונות חלל פנימי של בית. נסו תמונות בהירות יותר, ורצוי אחת לכל חדר.',
      'no-photos': 'צריך לפחות תמונה אחת.',
      'not-configured': 'מנוע הזיהוי עדיין לא מחובר. אפשר בינתיים לבנות את הסיור ידנית.',
      busy: 'המערכת עמוסה כרגע. נסו שוב בעוד רגע.',
      timeout: 'הזיהוי לקח יותר מדי זמן. נסו עם פחות תמונות.',
      refused: 'לא הצלחתי לנתח את התמונות האלה.',
      network: 'אין חיבור לרשת.',
      failed: 'משהו השתבש. נסו שוב.',
    },
    photosNote: 'התמונות משמשות לבניית הדירה — הן לא נתלות על הקירות.',
    manualBuild: 'בניה ידנית',
    surveyed: 'נבנה מהתמונות',
    roomsFound: 'החדרים שזוהו',
    editNote: 'אפשר לשנות כל פרט לפני השליחה.',

    /* the uploader */
    dropTitle: 'גררו תמונות לכאן',
    dropHint: 'או בחרו מהמכשיר · עד {max} תמונות',
    choosePhotos: 'בחירת תמונות',
    takePhoto: 'צילום',
    uploading: 'מעלה…',
    uploadedCount: '{n} תמונות מוכנות',
    uploadFull: 'הגעתם ל־{max} תמונות. הסירו אחת כדי להוסיף אחרת.',
    removePhoto: 'הסרת התמונה',
    retry: 'נסו שוב',
    storageOff: 'האחסון עדיין לא מחובר, אז אי אפשר להעלות תמונות כרגע. אפשר לבנות את הסיור בלעדיהן.',
    photosLabel: 'תמונות מהנכס',
    errors: {
      'storage-not-configured': 'אין אחסון',
      'bucket-missing': 'האחסון לא מוכן',
      'not-allowed': 'אין הרשאה',
      'too-large': 'כבדה מדי',
      network: 'אין רשת',
      failed: 'נכשל',
    },
  },
  en: {
    dir: 'ltr',
    tour: 'Property tour',
    rooms: 'Rooms',
    size: 'Size',
    floor: 'Floor',
    sqm: 'm²',
    price: 'Price',
    details: 'Property details',
    contact: 'Contact me',
    call: 'Call',
    photos: 'Photos',
    walkHint: 'Drag to look · joystick to walk',
    entrance: 'Entrance',
    living: 'Living & kitchen',
    livingClosed: 'Living room',
    master: 'Main bedroom',
    bedroom2: 'Bedroom 2',
    bedroom3: 'Bedroom 3',
    bedroom4: 'Bedroom 4',
    bath: 'Bathroom',
    bath2: 'WC',
    kitchen: 'Kitchen',
    balcony: 'Balcony',
    openKitchen: 'Open kitchen',
    elevator: 'Lift',
    note: 'A generated model of the layout. The real photographs are shown inside the tour and in the gallery.',
    studioTitle: 'Tour builder',
    studioSub: 'Describe the property, get a link, send it to your client',
    property: 'Property',
    agentSection: 'Agent details',
    title: 'Title',
    address: 'Address',
    bedroomsLabel: 'Bedrooms',
    bathroomsLabel: 'Bathrooms',
    sizeLabel: 'Size in m²',
    floorLabel: 'Floor',
    agentName: 'Name',
    agency: 'Agency',
    phone: 'Phone',
    preview: 'Preview',
    createLink: 'Create a link to send',
    copied: 'Link copied',
    sendWhatsapp: 'Send on WhatsApp',
    openTour: 'Open the tour',
    linkReady: 'Your link is ready',

    /* landing page */
    landTitle: 'Your listing. A 3D tour. One link.',
    landSub:
      'Upload the photographs, fill in a few details, and get a link your client opens on their phone and walks through — no app, no sign-up, no camera crew.',
    landCta: 'Start with the photos',
    landSecondary: 'See an example tour',
    landPhotosTitle: 'Photographs of the property',
    landPhotosSub: 'They hang on the walls inside the tour and appear in the gallery. You can also go without them.',
    landContinue: 'Continue to the builder',
    landSkip: 'Skip — build it without photos',
    landStepsTitle: 'How it works',
    landStep1: 'Upload photos',
    landStep1Body: 'Straight from the phone, the camera or the desktop. We shrink them so the tour opens fast.',
    landStep2: 'Fill in the details',
    landStep2Body: 'Rooms, size, floor, balcony. That becomes a floor plan you can walk around in.',
    landStep3: 'Send the link',
    landStep3Body: 'One link on WhatsApp. Your client opens it, walks through, and calls you from inside the tour.',
    landWhyTitle: 'Why it works',
    landWhy1: 'Fewer wasted viewings',
    landWhy1Body: 'Whoever turns up has already seen the place. Only the serious ones are left.',
    landWhy2: 'Ready in a minute',
    landWhy2Body: 'No scanner, no photographer, no arranging access to the property.',
    landWhy3: 'Works on any phone',
    landWhy3Body: 'An ordinary browser. Nothing to download and nothing to sign up for.',
    landHonest: 'Straight up: the tour is a model of the layout from the details you enter — not a scan of the flat itself. The real photographs are shown inside it and in the gallery.',
    landFooter: '3D property tours for estate agents',

    /* tagging each photo, so the browser can build without a model */
    tagTitle: 'What is in each photograph?',
    tagSub: 'Tap the kind of room under each one. Two photographs of the same room — tag both.',
    areaLabel: 'Size of the flat in m²',
    areaHint: 'The figure from the listing. Room sizes are shared out from it.',
    buildFree: 'Build the home',
    needTags: 'Tag at least one photograph to start.',
    reading2: 'Reading the photographs…',
    readNote: 'The colours, floors and windows are read from your photographs. The furniture is standard, in the colours read from that room.',
    whatWasRead: 'What was read from the photos',
    floorKinds: {
      wood: 'Wood',
      tile: 'Tile',
      stone: 'Stone',
      carpet: 'Carpet',
      vinyl: 'Vinyl',
      concrete: 'Concrete',
    },
    hasWindow: 'Window',
    unknownPhoto: 'Not tagged',
    taggedCount: '{n} of {total} photos tagged',

    /* reading the photos into a home */
    buildHouse: 'Build the home from the photos',
    reading: 'Reading the photographs…',
    readingStep1: 'Finding the rooms',
    readingStep2: 'Measuring them',
    readingStep3: 'Reading colours and materials',
    readingStep4: 'Building the flat',
    readingWait: 'This takes thirty seconds to a minute. Keep this page open.',
    surveyDone: 'The home is ready',
    surveyRooms: '{n} rooms found',
    tryAgain: 'Try again',
    surveyErrors: {
      unreadable: 'I could not make out the inside of a home in those photographs. Try brighter ones, ideally one per room.',
      'no-photos': 'At least one photograph is needed.',
      'not-configured': 'The survey engine is not connected yet. You can still build the tour by hand.',
      busy: 'Everything is busy right now. Try again in a moment.',
      timeout: 'That took too long. Try again with fewer photographs.',
      refused: 'I could not analyse those photographs.',
      network: 'No network connection.',
      failed: 'Something went wrong. Try again.',
    },
    photosNote: 'The photographs are used to build the flat — they are not hung on its walls.',
    manualBuild: 'Build by hand',
    surveyed: 'Built from the photos',
    roomsFound: 'Rooms found',
    editNote: 'You can change any detail before you send it.',

    /* the uploader */
    dropTitle: 'Drop photos here',
    dropHint: 'or pick them from your device · up to {max}',
    choosePhotos: 'Choose photos',
    takePhoto: 'Camera',
    uploading: 'Uploading…',
    uploadedCount: '{n} photos ready',
    uploadFull: 'That is {max} photos. Remove one to add another.',
    removePhoto: 'Remove photo',
    retry: 'Try again',
    storageOff: 'Storage is not connected yet, so photos cannot be uploaded right now. You can still build the tour without them.',
    photosLabel: 'Property photos',
    errors: {
      'storage-not-configured': 'No storage',
      'bucket-missing': 'Storage not ready',
      'not-allowed': 'Not allowed',
      'too-large': 'Too large',
      network: 'No network',
      failed: 'Failed',
    },
  },
};

export function pickLang() {
  try {
    const n = (navigator.language || '').toLowerCase();
    if (n.startsWith('en')) return 'en';
  } catch {
    /* default below */
  }
  return 'he';
}
