/** Hebrew first — the product is aimed at Israeli agents. */
export const LANGS = {
  he: {
    dir: 'rtl',
    tour: 'סיור בנכס',
    rooms: 'חדרים',
    size: 'שטח',
    floor: 'קומה',
    sqm: 'מ״ר',
    price: 'מחיר',
    details: 'פרטי הנכס',
    contact: 'דברו איתי',
    call: 'חיוג',
    photos: 'תמונות מהנכס',
    walkHint: 'גרור כדי להסתכל · ג׳ויסטיק כדי ללכת',
    entrance: 'כניסה',
    living: 'סלון ומטבח',
    livingClosed: 'סלון',
    master: 'חדר שינה',
    bedroom2: 'חדר 2',
    bedroom3: 'חדר 3',
    bedroom4: 'חדר 4',
    bath: 'אמבטיה',
    bath2: 'שירותים',
    kitchen: 'מטבח',
    balcony: 'מרפסת',
    openKitchen: 'מטבח פתוח',
    elevator: 'מעלית',
    note: 'הדמיה של תכנית הנכס. התמונות האמיתיות מוצגות בתוך הסיור ובגלריה.',
    studioTitle: 'בונה הסיורים',
    studioSub: 'מלאו את פרטי הנכס, קבלו קישור, שלחו ללקוח',
    property: 'הנכס',
    agentSection: 'פרטי המתווך',
    title: 'כותרת',
    address: 'כתובת',
    bedroomsLabel: 'חדרי שינה',
    bathroomsLabel: 'חדרי רחצה',
    sizeLabel: 'שטח במ״ר',
    floorLabel: 'קומה',
    agentName: 'שם',
    agency: 'משרד',
    phone: 'טלפון',
    photoUrls: 'קישורים לתמונות (שורה לכל תמונה)',
    preview: 'תצוגה מקדימה',
    createLink: 'צור קישור לשליחה',
    copied: 'הקישור הועתק',
    sendWhatsapp: 'שליחה בוואטסאפ',
    openTour: 'פתח את הסיור',
    linkReady: 'הקישור מוכן',
  },
  en: {
    dir: 'ltr',
    tour: 'Property tour',
    rooms: 'Rooms',
    size: 'Size',
    floor: 'Floor',
    sqm: 'm²',
    price: 'Price',
    details: 'Property details',
    contact: 'Contact me',
    call: 'Call',
    photos: 'Photos',
    walkHint: 'Drag to look · joystick to walk',
    entrance: 'Entrance',
    living: 'Living & kitchen',
    livingClosed: 'Living room',
    master: 'Main bedroom',
    bedroom2: 'Bedroom 2',
    bedroom3: 'Bedroom 3',
    bedroom4: 'Bedroom 4',
    bath: 'Bathroom',
    bath2: 'WC',
    kitchen: 'Kitchen',
    balcony: 'Balcony',
    openKitchen: 'Open kitchen',
    elevator: 'Lift',
    note: 'A generated model of the layout. The real photographs are shown inside the tour and in the gallery.',
    studioTitle: 'Tour builder',
    studioSub: 'Describe the property, get a link, send it to your client',
    property: 'Property',
    agentSection: 'Agent details',
    title: 'Title',
    address: 'Address',
    bedroomsLabel: 'Bedrooms',
    bathroomsLabel: 'Bathrooms',
    sizeLabel: 'Size in m²',
    floorLabel: 'Floor',
    agentName: 'Name',
    agency: 'Agency',
    phone: 'Phone',
    photoUrls: 'Photo links (one per line)',
    preview: 'Preview',
    createLink: 'Create a link to send',
    copied: 'Link copied',
    sendWhatsapp: 'Send on WhatsApp',
    openTour: 'Open the tour',
    linkReady: 'Your link is ready',
  },
};

export function pickLang() {
  try {
    const n = (navigator.language || '').toLowerCase();
    if (n.startsWith('en')) return 'en';
  } catch {
    /* default below */
  }
  return 'he';
}
